version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-d179110dl3ps73a66qpg-a
      - DB_PORT=5432
      - DB_DATABASE=production_db_asio
      - DB_USERNAME==production_db_asio_user
      - DB_PASSWORD=XAatsS4CCGJPMtBYdEPzZ3Gp1nm09Ptx
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel: