services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:sPuk5Hx+DC+3PDh0MXtqjciGif+yFbRU+2AbWlKLgGk=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-mysql-host>.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-db-name>
      - key: DB_USERNAME
        value: <your-db-user>
      - key: DB_PASSWORD
        value: <your-db-password>
